archive-dir: /home/acrease/Documents/c77mods/archives
# game-dir: /home/acrease/.steam/steam/steamapps/common/Cyberpunk 2077
game-dir: /home/acrease/Documents/c77mods/test-game-dir
save-file: save.pkl
profiles:
  default:
    whitelist: "*"
  zero:
    blacklist: "*"
  include:
    blacklist: "*"
    include: ["mod_settings.zip-4885-0-2-8-1710978150.zip"]
  exclude:
    whitelist: "*"
    exclude: ["mod_settings.zip-4885-0-2-8-1710978150.zip"]
    # Default profile extracts all mods

# PROFILE SCHEMA
# default:
#   whitelist: "regex"
#   blacklist: "regex"
#   include: ["filenames"]
#   exclude: ["filenames"]
